=== Tiliavir/mvw-website/Source/assets/pages/data/schema/berichte-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for my JSON file format",

  "type": "array",

  "items": {
    "properties": {
      "date": {
        "type": "string",
        "format": "date-time"
      },
      "title": {
        "type": "string"
      },
      "url": {
        "type": "string"
      },
      "hasPicture": {
        "type": "boolean",
        "default": false
      },
      "hasDescription": {
        "type": "boolean",
        "default": false
      },
      "srcTitle": {
        "type": "string"
      },
      "srcUrl": {
        "type": "string"
      }
    },
    "additionalProperties": false,
    "required": [ "date", "title", "url", "srcTitle", "srcUrl" ]
  },
  "additionalItems": false
}

=== Tiliavir/mvw-website/Source/assets/pages/data/berichte.json
[
  {
    "date": "2016-01-11T00:00:00Z",
    "url": "https://www.badische-zeitung.de/kandern/hochwasserschutz-auch-fuer-wollbach-thema--116049947.html",
    "title": "Hochwasserschutz auch für Wollbach Thema",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2016-01-09T00:00:00Z",
    "url": "http://www.verlagshaus-jaumann.de/inhalt.kandern-150-jahre-musikverein-wollbach.01050027-6d9d-4713-a0e7-21cea19a09c8.html",
    "title": "150 Jahre Musikverein Wollbach",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.verlagshaus-jaumann.de",
    "srcTitle": "VHJ"
  },
  {
    "date": "2016-01-07T00:00:00Z",
    "url": "https://www.badische-zeitung.de/kandern/landesehrennadel-fuer-vorsitzende-annette-krey--115925585.html",
    "title": "Landesehrennadel für Vorsitzende Annette Krey",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2016-01-08T00:00:00Z",
    "url": "https://www.badische-zeitung.de/kandern/geburtstagsfeiern-uebers-ganze-jahr--115972314.html",
    "title": "Geburtstagsfeiern übers ganze Jahr",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2015-12-10T00:00:00Z",
    "url": "https://www.badische-zeitung.de/kandern/jugendvorspiel-beim-musikverein-wollbach--114897226.html",
    "title": "Jugendvorspiel beim Musikverein Wollbach",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2015-11-26T00:00:00Z",
    "url": "https://www.badische-zeitung.de/kandern/wartburgfest-in-der-kandertalhalle--114149352.html",
    "title": "Wartburgfest in der Kandertalhalle",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2015-12-01T00:00:00Z",
    "url": "https://www.badische-zeitung.de/kreis-loerrach/edelmetall-fuer-junge-blasmusiker--114534257.html",
    "title": "Edelmetall für junge Blasmusiker",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2015-10-23T00:00:00Z",
    "url": "https://www.badische-zeitung.de/kandern/froehliche-blasmusik-zu-herbstlicher-hausmannskost--112875733.html",
    "title": "Fröhliche Blasmusik zu herbstlicher Hausmannskost",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2015-05-23T00:00:00Z",
    "url": "https://www.badische-zeitung.de/kandern/ein-zweiter-foerderverein-fuer-wollbachs-musiker--105231944.html",
    "title": "Ein zweiter Förderverein für Wollbachs Musiker",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2015-01-26T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/groovende-symbiose-aus-klassik-und-rock--99486554.html",
    "title": "Groovende Symbiose aus Klassik und Rock",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2015-01-25T00:00:00Z",
    "url": "http://www.verlagshaus-jaumann.de/inhalt.kandern-musik-die-zum-staunen-anregt.32041209-7649-416c-9c9e-7ab9783e63f8.html",
    "title": "Musik, die zum Staunen anregt",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.verlagshaus-jaumann.de",
    "srcTitle": "VHJ"
  },
  {
    "date": "2014-10-27T00:00:00Z",
    "url": "http://www.badische-zeitung.de/bad-saeckingen/singende-gaeste-swingende-gastgeber--93546393.html",
    "title": "Singende Gäste, swingende Gastgeber",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2014-01-20T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/lateinamerikas-bunte-klangwelt--79826974.html",
    "title": "Latainamerikas bunte Klangwelt",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2013-06-10T00:00:00Z",
    "url": "http://www.bernerzeitung.ch/region/emmental/Beschwingter-Marsch-in-den-Musiksommer/story/21884440",
    "title": "Beschwingter Marsch in den Musiksommer",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.bernerzeitung.ch/",
    "srcTitle": "BZ"
  },
  {
    "date": "2013-04-16T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/wollbacher-musiker-in-topform--70919643.html",
    "title": "Wollbacher Musiker in Topform",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2013-01-22T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/blaesersinfonik-voller-klangpracht",
    "title": "Bläsersinfonik voller Klangpracht",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2010-01-28T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/erfolgsgaranten-geehrt",
    "title": "Erfolgsgaranten geehrt",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2010-01-09T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/junge-talente-bei-der-musik",
    "title": "Junge Talente bei der Musik",
    "hasPicture": false,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2009-10-26T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/der-herbst-in-allen-facetten-in-die-halle-geholt",
    "title": "Der Herbst in allen Facetten in die Halle geholt",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2009-08-01T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/15-750-euro-fuer-vereine--17819718.html",
    "title": "15750 Euro für Vereine",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2009-06-22T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/gute-musik-gutes-essen",
    "title": "Gute Musik, gutes Essen",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2009-04-20T00:00:00Z",
    "url": "http://www.badische-zeitung.de/kandern/von-gefuehlvoll-bis-pathetisch--13717641.html",
    "title": "Von gefühlvoll bis pathetisch",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2009-02-02T00:00:00Z",
    "url": "http://www.badische-zeitung.de/monika-hurst-lobt-den-musikverein",
    "title": "Monika Hurst lobt den Musikverein",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2009-01-21T00:00:00Z",
    "url": "http://www.badische-zeitung.de/zwei-neue-ehrenmitglieder-x1x",
    "title": "Zwei neue Ehrenmitglieder",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2009-01-20T00:00:00Z",
    "url": "http://www.badische-zeitung.de/mit-spanischer-leidenschaft",
    "title": "Mit spanischer Leidenschaft",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2009-01-19T00:00:00Z",
    "url": "http://www.oberbadisches-volksblatt.de/core.php?dat=Y29tcG9uZW50PW5ld3MmYWN0aW9uPXNob3cmeElEPW5ld3NCeUlEJm5ld3NJRD00MTA1MjEmcGFyZW50SUQ9Jm5hdmlnYXRpb25JRD0=",
    "title": "Ehrungen beim Jahreskonzert",
    "hasPicture": false,
    "hasDescription": true,
    "srcUrl": "http://www.oberbadisches-volksblatt.de/",
    "srcTitle": "VHJ"
  },
  {
    "date": "2009-01-19T00:00:00Z",
    "url": "http://www.oberbadisches-volksblatt.de/core.php?dat=Y29tcG9uZW50PW5ld3MmYWN0aW9uPXNob3cmeElEPW5ld3NCeUlEJm5ld3NJRD00MTA0NzUmcGFyZW50SUQ9Jm5hdmlnYXRpb25JRD0=",
    "title": "Musikverein Wollbach bot beim Jahreskonzert spanische Klänge",
    "hasPicture": false,
    "hasDescription": true,
    "srcUrl": "http://www.oberbadisches-volksblatt.de/",
    "srcTitle": "VHJ"
  },
  {
    "date": "2008-12-02T00:00:00Z",
    "url": "http://www.badische-zeitung.de/siebenmal-gold-das-gab-es-bislang-noch-nie",
    "title": "Siebenmal Gold",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2008-10-22T00:00:00Z",
    "url": "http://www.badische-zeitung.de/ein-farbtupfer-im-festkalender",
    "title": "Herbstfest",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2008-10-17T00:00:00Z",
    "url": "http://www.badische-zeitung.de/nachrichten/1,51-25606999.html",
    "title": "Herbstfest mit musikalischem Reigen",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2008-08-27T00:00:00Z",
    "url": "http://www.badische-zeitung.de/lokales/lokalausgaben/weil/kandertal/34,51-24335827.html",
    "title": "Fahrt mit dem Sauser-Express",
    "hasPicture": true,
    "hasDescription": true,
    "srcUrl": "http://www.badische-zeitung.de",
    "srcTitle": "BZ"
  },
  {
    "date": "2008-06-21T00:00:00Z",
